add_newline = false

format = """
$directory$git_branch$git_status$cmd_duration$time
$character"""

[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "../"

[git_branch]
symbol = "git:"
style = "bold magenta"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "[$all_status$ahead_behind]($style) "
modified = "!${count} "
staged = "+${count} "
untracked = "?${count} "
ahead = "^${count} "
behind = "v${count} "

[cmd_duration]
min_time = 500
style = "yellow"
format = "[$duration]($style) "

[time]
disabled = false
time_format = "%H:%M:%S"
style = "dimmed white"
format = "[$time]($style)"

[character]
success_symbol = ">"
error_symbol = ">"
